export enum DiagramTypes {
    LOCATION_FROM = 'LOCATION_FROM',
    LOCATION_TO = 'LOCATION_TO',
    CHARACTER_ATTRIBUTES = 'CHARACTER_ATTRIBUTES',
    ITEM_GRAB = 'ITEM_GRAB',
    NPC_TALK = 'NPC_TALK',
    ATTRIBUTE_INCREASE = 'ATTRIBUTE_INCREASE',
    ATTRIBUTE_DECREASE = 'ATTRIBUTE_DECREASE',
    ITEM_USE = 'ITEM_USE',
    KILL_ENEMY = 'KILL_ENEMY',
    ATTACK_ENEMY = 'ATTACK_ENEMY',
    GET_ITEM_FROM_NPC = 'GET_ITEM_FROM_NPC',
    GIVE_ITEM_TO_NPC = 'GIVE_ITEM_TO_NPC',
}
