export enum DiagramTypes {
    LOCATION_FROM = 'LOCATION_FROM',
    LOCATION_TO = 'LOCATION_TO',
    CHARACTER_ATTRIBUTES = 'CHARACTER_ATTRIBUTES',
    ITEM_GRAB = 'ITEM_GRAB',
    NPC_TALK = 'NPC_TALK',
    ATTRIBUTE_INCREASE = 'ATTRIBUTE_INCREASE',
    ATTRIBUTE_DECREASE = 'ATTRIBUTE_DECREASE',
    ITEM_USE = 'ITEM_USE',
}
